config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  scope '/images' do
    get '/search', to: 'images#search', as: :search_images
    post '/favorite', to: 'images#favorite', as: :favorite_image
    get '/favorites', to: 'images#favorites', as: :favorite_images
  end

  root to: 'pages#home'
end

app/models/application_record.rb
# frozen_string_literal: true

# Application Record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
# frozen_string_literal: true

# Image Model
class Image < ApplicationRecord
  belongs_to :user

  validates :id_unsplash, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true
end

app/models/user.rb
# frozen_string_literal: true

# User Model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable

  before_validation { self.email = email.downcase if email.present? }
  before_validation { self.username = username.downcase if username.present? }

  has_many :images, dependent: :destroy

  USERNAME_REGEXP = /\A(?!.*\.\.)(?!.*\.$)[^\W][\w.]{0,29}\z/.freeze
  validates :username, presence: true, format: { with: USERNAME_REGEXP }, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application Controller
class ApplicationController < ActionController::Base
  include Pagy::Backend

  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username])
  end
end

app/controllers/images_controller.rb
# frozen_string_literal: true

# Images Controller
class ImagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :search

  def search
    @page = params[:page] || 1
    @images = Unsplash::Photo.search(params[:q], @page, 9)
    render json: {
      entries: render_to_string(
        partial: 'images/image_unsplash',
        collection: @images,
        as: :image,
        formats: [:html]
      )
    }
  end

  def favorite
    @image = Image.find_by(id_unsplash: params[:image][:id_unsplash])
    if @image
      @image.destroy
    else
      @image = current_user.images.create(image_params)
    end
  end

  def favorites
    @pagy, @images = pagy(current_user.images)

    respond_to do |format|
      format.html
      format.json do
        render json: { entries: render_to_string(partial: 'images/image', collection: @images,
                                                 as: :image, formats: [:html]),
                       next: !@pagy.next.nil? }
      end
    end
  end

  private

  def image_params
    params.require(:image).permit(:id_unsplash, :url)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# Pages Controller
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Application Helper
module ApplicationHelper
end

app/helpers/images_helper.rb
# frozen_string_literal: true

# Application Helper
module ImagesHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

# Pages Helper
module PagesHelper
end

app/views/images/_image.html.erb
<div class="column is-12-mobile is-6-tablet is-4-desktop">
  <div class="card mx-1" data-controller="favorite" data-favorite-url="<%= favorite_image_path %>"
       data-favorite-id-unsplash="<%= image.id_unsplash %>" data-favorite-url-unsplash="<%= image.url %>">
    <div class="card-image has-text-centered">
      <figure class="image" style= "cursor: pointer;">
        <%= image_tag image.url, alt: 'Image', data: { action: 'click->modal#open' } %>
      </figure>
    </div>
    <div class="card-content py-0 px-0">
      <p class="has-text-centered" style="width: 100%">
        <i class="fas fa-heart liked" style= "cursor: pointer;" data-target="favorite.heart" data-action="click->favorite#submit"></i>
      </p>
    </div>
  </div>
</div>

app/views/images/_image_unsplash.html.erb
<div class="column is-12-mobile is-6-tablet is-4-desktop">
  <% if user_signed_in? %>
    <div class="card mx-1" data-controller="favorite" data-favorite-url="<%= favorite_image_path %>"
         data-favorite-id-unsplash="<%= image.id %>" data-favorite-url-unsplash="<%= image.urls.raw %>">
      <div class="card-image has-text-centered">
        <figure class="image" style= "cursor: pointer;">
          <%= image_tag image.urls.raw, alt: 'Image', data: { action: 'click->modal#open' } %>
        </figure>
      </div>
      <div class="card-content py-0 px-0">
        <p class="has-text-centered" style="width: 100%">
          <i class="fas fa-heart not_liked" style= "cursor: pointer;" data-target="favorite.heart" data-action="click->favorite#submit"></i>
        </p>
      </div>
    </div>
  <% else %>
    <div class="card mx-1">
      <div class="card-image has-text-centered">
        <figure class="image" style= "cursor: pointer;">
          <%= image_tag image.urls.raw, alt: 'Image', data: { action: 'click->modal#open' } %>
        </figure>
      </div>
    </div>
  <% end %>
</div>

app/views/images/_modal.html.erb
<div class="modal" data-target="modal.container">
  <div class="modal-background" data-target="modal.background" data-action="click->modal#closeBackground keyup@window->modal#closeWithKeyboard"></div>
  <div class="modal-content">
    <p class="image">
      <%= image_tag '', id: 'image_modal', alt: 'Image', data: { target: 'modal.image' } %>
    </p>
  </div>
  <button class="modal-close is-large" aria-label="close" data-action="click->modal#close"></button>
</div>

app/views/images/favorites.html.erb
<div class="container">
  <div class="columns">
    <div class="column is-12-mobile is-10-tablet is-offset-1-tablet has-text-centered mt-6 pr-0"
         data-controller="infinite-scroll" data-infinite-scroll-url="<%= favorite_images_path %>"
         data-infinite-scroll-page="2" data-infinite-scroll-active="<%= !!@pagy.next %>">
      <h2 class="title is-2 is-uppercase">Your favorite images</h2>

      <div class="mt-6" data-controller="modal">
        <%= render partial: 'images/modal' %>
        <div class="columns is-multiline"
             data-action="scroll@window->infinite-scroll#scroll"
             data-target="infinite-scroll.entries">

          <% if @images.size > 0 %>
            <%= render partial: 'images/image', collection: @images, as: :image %>
          <% else %>
            <div class="has-text-centered" style="width: 100%;">
              <h4 class="mt-6 subtitle is-4">This is empty, start to find images and mark them as favorites!</h4>
            </div>
          <% end %>
        </div>
        <div class="lds-ring is-hidden" data-target="infinite-scroll.loading"><div></div><div></div><div></div><div></div></div>
      </div>
    </div>
  </div>
</div>

app/views/images/favourites.html.erb
<div class="container">
  <div class="columns">
    <div class="column is-12-mobile is-10-tablet is-offset-1-tablet has-text-centered mt-6"
         data-controller="infinite-scroll" data-infinite-scroll-url="<%= favourite_images_path %>"
         data-infinite-scroll-page="2" data-infinite-scroll-active="<%= !!@pagy.next %>">
      <h2 class="title is-2">Your favourite images</h2>

      <div class="mt-6" data-controller="modal">
        <%= render partial: 'images/modal' %>
        <div class="columns is-multiline"
             data-action="scroll@window->infinite-scroll#scroll"
             data-target="infinite-scroll.entries">

          <% if @images.size > 0 %>
            <%= render partial: 'images/image', collection: @images, as: :image %>
          <% else %>
            <div class="has-text-centered" style="width: 100%;">
              <h4 class="mt-6 subtitle is-4">This is empty, start to find images and mark as favourite!</h4>
            </div>
          <% end %>
        </div>
        <div class="lds-ring is-hidden" data-target="infinite-scroll.loading"><div></div><div></div><div></div><div></div></div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="has-navbar-fixed-top">
  <head>
    <title>IdeawareHomeTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/079ea5cde4.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>

    <%= render partial: 'shared/alerts' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="columns">
    <div class="column is-12-mobile is-10-tablet is-offset-1-tablet has-text-centered mt-6 pr-0"
         data-controller="infinite-scroll" data-infinite-scroll-url="<%= search_images_path %>"
         data-infinite-scroll-page="1" data-infinite-scroll-active="true">
        <div class="field">
          <label for="search" class="label title is-3 mb-3 is-uppercase">Search</label>
          <p class="control has-icons-left mx-2">
            <input type="text" name="search" id"="search" class="input"
                   placeholder="Please type in what you wish to search for, e.g., dogs, lakes, mountains"
                   data-target="infinite-scroll.search" data-action="keyup@window->infinite-scroll#submit">
            <span class="icon is-left"><i class="fas fa-search"></i></span>
          </p>
        </div>

      <div class="mt-5" data-controller="modal">
        <%= render partial: 'images/modal' %>
        <div class="columns is-multiline"
             data-action="scroll@window->infinite-scroll#scroll"
             data-target="infinite-scroll.entries"></div>
        <div class="lds-ring is-hidden" data-target="infinite-scroll.loading"><div></div><div></div><div></div><div></div></div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_alerts.html.erb
<% if notice %>
  <section class="hero is-info">
    <div class="hero-body">
      <div class="container">
        <h2 class="subtitle is-4">
          <%= notice %>
        </h2>
      </div>
    </div>
  </section>
<% end %>

<% if alert %>
  <section class="hero is-danger">
    <div class="hero-body">
      <div class="container">
        <h2 class="subtitle is-4">
          <%= alert %>
        </h2>
      </div>
    </div>
  </section>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to 'Ideaware Home Test', root_path, class: 'navbar-item is-uppercase' %>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbar">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbar" class="navbar-menu">
    <div class="navbar-end">
      <a href="https://github.com/dmunoz-10/ideaware_home_test" target="_blank" class="navbar-item is-uppercase">GitHub</a>

      <% if user_signed_in? %>
        <%= link_to 'Favorites', favorite_images_path, class: 'navbar-item is-uppercase' %>

        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link is-rounded">
            <img src="https://api.adorable.io/avatars/40/<%= current_user.username %>.png" alt="Users' avatar" style="border-radius: 50%">
          </a>

          <div class="navbar-dropdown" style="left: -50px !important">
            <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-item is-uppercase' %>

            <hr class="navbar-divider">

            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'navbar-item is-uppercase' %>
          </div>
        </div>
      <% else %>
        <%= link_to 'Sign up', new_user_registration_path, class: 'navbar-item is-uppercase' %>
        <%= link_to 'Sign in', user_session_path, class: 'navbar-item is-uppercase' %>
      <% end %>
    </div>
  </div>
</nav>